jobs:
- job: build
  displayName: Build & Test
  strategy:
    matrix:
      linux:
        vmImage: 'ubuntu-latest'
        target: x86_64-unknown-linux-gnu
      windows64:
        vmImage: 'windows-latest'
        target: x86_64-pc-windows-msvc
      windows32:
        vmImage: 'windows-latest'
        target: i686-pc-windows-msvc
  
  pool:
    vmImage: $(vmImage)

  steps:
  - script: rustup target add $(target)
    displayName: rustup add target

  - script: cargo build --release --verbose --target $(target)
    displayName: 'build'

  - script: cargo test --verbose --workspace --target $(target)
    displayName: test

  - task: CopyFiles@2
    inputs:
      Contents: |
        target/$(target)/release/rnc
        target/$(target)/release/rnc.exe
      TargetFolder: '$(build.artifactstagingdirectory)'
      flattenFolders: true

  - powershell: |
      $rnc_version = & $(Build.ArtifactStagingDirectory)/rnc --version
      Write-Host "##vso[task.setvariable variable=rnc_version]$rnc_version"

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: $(Build.ArtifactStagingDirectory)
      artifact: $(RNC_VERSION)-$(target)
      publishLocation: 'pipeline'
