[package]
name = "rnc"
version = "0.1.0"
authors = ["Michal Borejszo <michael.borejszo@gmail.com>"]
edition = "2018"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.1"
content_inspector = "0.2.4"

[lib]
name = "rnc"
path = "src/lib.rs"

[[bin]]
name = "rnc"
path = "src/bin/main.rs"
