name: Check Build

on:
  pull_request:
    branches: [master]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        toolchain: [stable, msrv-lib, msrv-bin]
        include:
          - toolchain: stable
            rust: stable
            args: ""
          - toolchain: msrv-lib
            rust: 1.38.0
            args: "-p newline-converter"
          - toolchain: msrv-bin
            rust: 1.40.0
            args: ""

    runs-on: ubuntu-latest

    env:
      RUSTFLAGS: "--deny warnings"

    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ matrix.rust }}
      - name: Build
        run: cargo build --verbose ${{ matrix.args }}

  test:
    runs-on: ubuntu-latest

    env:
      RUSTFLAGS: "--deny warnings"

    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
      - name: Run tests
        run: cargo test --verbose

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
      - name: Check code formatting
        run: cargo fmt -- --check
      - name: Run Clippy
        run: cargo clippy --all -- --deny warnings

  done:
    name: Done
    needs: [build, test, lint]
    runs-on: ubuntu-latest
    steps:
      - name: Done
        run: echo Done
