name: Check Build

on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        toolchain: [stable, msrv-lib, msrv-bin]
        include:
        - toolchain: stable
          rust: stable
          args: ""
        - toolchain: msrv-lib
          rust: 1.38.0
          args: "-p newline-converter"
        - toolchain: msrv-bin
          rust: 1.40.0
          args: ""

    runs-on: ubuntu-latest
    
    env:
      RUSTFLAGS: "--deny warnings"

    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: ${{ matrix.rust }}
        override: true
    - name: Build
      run: cargo build --verbose ${{ matrix.args }}
  
  test:
    runs-on: ubuntu-latest
    
    env:
      RUSTFLAGS: "--deny warnings"

    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
    - name: Run tests
      run: cargo test --verbose

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
        components: rustfmt, clippy
    - name: Check code formatting
      run: cargo fmt -- --check
    - name: Run Clippy
      uses: actions-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        args: --all-features

  done:
    name: Done
    needs: [build, test, lint]
    runs-on: ubuntu-latest
    steps:
      - name: Done
        run: echo Done
